export const PACKAGES = [
  {
    id: 1,
    date: new Date(),
    firstName: 'James',
    lastName: 'Bron',
    nbPackage: 2,
    avatar: require('../../assets/user.png'),
    code: '362J',
  },
  {
    id: 2,
    date: new Date(),
    firstName: 'Lucie',
    lastName: 'Dana',
    nbPackage: 1,
    avatar: require('../../assets/user1.png'),
    code: null,
  },
  {
    id: 3,
    date: new Date(),
    firstName: 'Jean',
    nbPackage: 2,
    avatar: require('../../assets/user3.png'),
    code: '934O',
  },
  {
    id: 4,
    date: new Date(),
    firstName: 'Marie',
    lastName: 'Larue',
    nbPackage: 2,
    avatar: require('../../assets/user2.png'),
    code: '834L',
  },
  {
    id: 5,
    date: new Date(),
    firstName: 'Pascal',
    lastName: 'LeGrand',
    nbPackage: 2,
    code: null,
  },
];
