export const PACKAGES = [
  {
    id: 1,
    date: new Date(),
    lastName: 'Bron',
    nbPackage: 2,
    avatar: require('../../assets/user.png'),
    code: '362J',
  },
  {
    id: 2,
    date: new Date(),
    lastName: 'Dana',
    nbPackage: 1,
    avatar: require('../../assets/user1.png'),
    code: null,
  },
  {
    id: 3,
    date: new Date(),
    lastName: 'Capliez',
    nbPackage: 2,
    avatar: require('../../assets/user3.png'),
    code: '934O',
  },
  {
    id: 4,
    date: new Date(),
    lastName: 'Hamida',
    nbPackage: 2,
    avatar: require('../../assets/user2.png'),
    code: '834L',
  },
  {
    id: 5,
    date: new Date(),
    lastName: 'LeGrand',
    nbPackage: 2,
    code: null,
  },
  {
    id: 6,
    date: new Date(),
    lastName: 'Durant',
    nbPackage: 3,
    code: null,
  },
  {
    id: 7,
    date: new Date(),
    lastName: 'Gomez',
    nbPackage: 3,
    code: null,
  },
];
