/**************************/
/********** AUTH **********/
/**************************/

/* SIGN IN */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

/* LOG OUT */
export const LOGOUT_USER = 'LOGOUT_USER';

/* SIGN IN WITH COOKIE */
export const LOGIN_USER_COOKIE = 'LOGIN_USER_COOKIE';
export const LOGIN_USER_SUCCESS_COOKIE = 'LOGIN_USER_SUCCESS_COOKIE';
export const LOGIN_USER_ERROR_COOKIE = 'LOGIN_USER_ERROR_COOKIE';

/* FORGOT PASSWORD */
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const EMPTY_FORGOT_PASSWORD_LOGIN = 'EMPTY_FORGOT_PASSWORD_LOGIN';

/* RESET PASSWORD */
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

/* VERIF TOKEN */
export const VERIFY_TOKEN = 'VERIFY_TOKEN';
export const VERIFY_TOKEN_SUCCESS = 'VERIFY_TOKEN_SUCCESS';
export const VERIFY_TOKEN_ERROR = 'VERIFY_TOKEN_ERROR';

/* CHANGE LOCAL */
export const CHANGE_LOCALE_USER = 'CHANGE_LOCALE_USER';
export const CHANGE_LOCALE_USER_SUCCESS = 'CHANGE_LOCALE_USER_SUCCESS';
export const CHANGE_LOCALE_USER_ERROR = 'CHANGE_LOCALE_USER_ERROR';

/* UPDATE */
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

/* NOTIFICATION */
export const EMPTY_ERROR_LOGIN = 'EMPTY_ERROR_LOGIN';
export const EMPTY_SUCCESS_USER = 'EMPTY_SUCCESS_USER';

/**************************/
/******* LANGUAGES ********/
/**************************/

/* GET ALL */
export const GET_LANGUAGES = 'GET_LANGUAGES';
export const GET_LANGUAGES_SUCCESS = 'GET_LANGUAGES_SUCCESS';
export const GET_LANGUAGES_ERROR = 'GET_LANGUAGES_ERROR';


/* NOTIFICATION */
export const EMPTY_ERROR_LANGUAGE = 'EMPTY_ERROR_LANGUAGE';
export const EMPTY_SUCCESS_LANGUAGE = 'EMPTY_SUCCESS_LANGUAGE';

/**************************/
/******* BUILDINGS ********/
/**************************/

/* GET ALL */
export const GET_BUILDINGS = 'GET_BUILDINGS';
export const GET_BUILDINGS_SUCCESS = 'GET_BUILDINGS_SUCCESS';
export const GET_BUILDINGS_ERROR = 'GET_BUILDINGS_ERROR';

/* GET BY */
export const GET_BUILDING_CURRENT = 'GET_BUILDING_CURRENT';
export const GET_BUILDING_CURRENT_SUCCESS = 'GET_BUILDING_CURRENT_SUCCESS';
export const GET_BUILDING_CURRENT_ERROR = 'GET_BUILDING_CURRENT_ERROR';

/* NOTIFICATION */
export const EMPTY_ERROR_BUILDING = 'EMPTY_ERROR_BUILDING';
export const EMPTY_SUCCESS_BUILDING = 'EMPTY_SUCCESS_BUILDING';

/**************************/
/******* RESIDENTS ********/
/**************************/

/* GET ALL */
export const GET_RESIDENTS = 'GET_RESIDENTS';
export const GET_RESIDENTS_SUCCESS = 'GET_RESIDENTS_SUCCESS';
export const GET_RESIDENTS_ERROR = 'GET_RESIDENTS_ERROR';

/* GET BY */
export const GET_RESIDENT_CURRENT = 'GET_RESIDENT_CURRENT';
export const GET_RESIDENT_CURRENT_SUCCESS = 'GET_RESIDENT_CURRENT_SUCCESS';
export const GET_RESIDENT_CURRENT_ERROR = 'GET_RESIDENT_CURRENT_ERROR';

/* POST */
export const REGISTER_RESIDENT = 'REGISTER_RESIDENT';
export const REGISTER_RESIDENT_SUCCESS = 'REGISTER_RESIDENT_SUCCESS';
export const REGISTER_RESIDENT_ERROR = 'REGISTER_RESIDENT_ERROR';

/* UPDATE */
export const UPDATE_RESIDENT = 'UPDATE_RESIDENT';
export const UPDATE_RESIDENT_SUCCESS = 'UPDATE_RESIDENT_SUCCESS';
export const UPDATE_RESIDENT_ERROR = 'UPDATE_RESIDENT_ERROR';

/* NOTIFICATION */
export const EMPTY_ERROR_RESIDENT = 'EMPTY_ERROR_RESIDENT';
export const EMPTY_SUCCESS_RESIDENT = 'EMPTY_SUCCESS_RESIDENT';

/**************************/
/******* PACKAGES *********/
/**************************/

/* GET ALL */
export const GET_PACKAGES = 'GET_PACKAGES';
export const GET_PACKAGES_SUCCESS = 'GET_PACKAGES_SUCCESS';
export const GET_PACKAGES_ERROR = 'GET_PACKAGES_ERROR';

/* GET BY */
export const GET_PACKAGE_CURRENT = 'GET_PACKAGE_CURRENT';
export const GET_PACKAGE_CURRENT_SUCCESS = 'GET_PACKAGE_CURRENT_SUCCESS';
export const GET_PACKAGE_CURRENT_ERROR = 'GET_PACKAGE_CURRENT_ERROR';

/* POST */
export const REGISTER_PACKAGE = 'REGISTER_PACKAGE';
export const REGISTER_PACKAGE_SUCCESS = 'REGISTER_PACKAGE_SUCCESS';
export const REGISTER_PACKAGE_ERROR = 'REGISTER_PACKAGE_ERROR';

/* NOTIFICATION */
export const EMPTY_ERROR_PACKAGE = 'EMPTY_ERROR_PACKAGE';
export const EMPTY_SUCCESS_PACKAGE = 'EMPTY_SUCCESS_PACKAGE';

/***************************/
/******* LANGUAGES *********/
/***************************/

/* GET ALL */
export const GET_LANGUAGES = 'GET_LANGUAGES';
export const GET_LANGUAGES_SUCCESS = 'GET_LANGUAGES_SUCCESS';
export const GET_LANGUAGES_ERROR = 'GET_LANGUAGES_ERROR';

/* NOTIFICATION */
export const EMPTY_ERROR_LANGUAGE = 'EMPTY_ERROR_LANGUAGE';
export const EMPTY_SUCCESS_LANGUAGE = 'EMPTY_SUCCESS_LANGUAGE';
